In [12]:
import os
import sys

import pandas as pd
import numpy as np

home_path = os.path.dirname(os.getcwd())
sys.path.append(home_path)

surce_path = os.path.join(os.path.dirname(os.getcwd()),'src')
sys.path.append(home_path)

from src.data_management import obtener_datos

## Preprocesamiento de datos

In [13]:
path_etiquetas = os.path.join(home_path, 'data', 'etiquetas.csv')
path_info_clientes = os.path.join(home_path, 'data', 'informacion_clientes.csv')
path_hist_transacciones = os.path.join(home_path, 'data', 'historial_transacciones.csv')

df = obtener_datos(path_etiquetas, path_info_clientes, path_hist_transacciones)
df.head(10)

Cupo_TC        SEX    EDUCATION  \
CLIENT_ID                                                               
29c55f5f-0da7-43ec-ba1b-b60592689825   270000   Femenino  universidad   
f818136a-138f-4578-a0bb-41605b67e0e5    80000   Femenino      colegio   
bef609a9-f9c5-4870-be7f-cb20e70f7e92   210000   Femenino  universidad   
2ba3a218-4792-4672-82c7-4b0953101d41   230000   Femenino      colegio   
723e61b4-d151-4368-b129-468417fd930c   130000   Femenino     Posgrado   
f689cc58-4331-40ba-ae4b-c43e649cb9e8   470000   Femenino  universidad   
5366b666-0978-4843-9ad0-a23993b94edd   800000  Masculino  universidad   
92825b72-b828-419b-b2b1-0c4791769558    20000  Masculino  universidad   
bd9b31c5-e0d6-4555-afab-ed6753d6afb8    40000  Masculino      colegio   
2c304969-82e6-4981-b2e2-af1f1977b47f    10000  Masculino  universidad   

                                       MARRIAGE  AGE  RETRASO_PAGO_ESTADO_4  \
CLIENT_ID                                                                     
29c55f5f-0da7-43ec-ba1b-b60592689825     Casado   28                      0   
f818136a-138f-4578-a0bb-41605b67e0e5  soltero_a   52                     -1   
bef609a9-f9c5-4870-be7f-cb20e70f7e92     Casado   36                      0   
2ba3a218-4792-4672-82c7-4b0953101d41     Casado   44                     -1   
723e61b4-d151-4368-b129-468417fd930c     Casado   36                      0   
f689cc58-4331-40ba-ae4b-c43e649cb9e8     Casado   35                      0   
5366b666-0978-4843-9ad0-a23993b94edd     Casado   53                     -1   
92825b72-b828-419b-b2b1-0c4791769558  soltero_a   30                      0   
bd9b31c5-e0d6-4555-afab-ed6753d6afb8  soltero_a   43                      7   
2c304969-82e6-4981-b2e2-af1f1977b47f  soltero_a   23                      7   

                                      RETRASO_PAGO_ESTADO_5  \
CLIENT_ID                                                     
29c55f5f-0da7-43ec-ba1b-b60592689825                      0   
f818136a-138f-4578-a0bb-41605b67e0e5                      0   
bef609a9-f9c5-4870-be7f-cb20e70f7e92                      0   
2ba3a218-4792-4672-82c7-4b0953101d41                     -1   
723e61b4-d151-4368-b129-468417fd930c                      0   
f689cc58-4331-40ba-ae4b-c43e649cb9e8                      0   
5366b666-0978-4843-9ad0-a23993b94edd                      0   
92825b72-b828-419b-b2b1-0c4791769558                      0   
bd9b31c5-e0d6-4555-afab-ed6753d6afb8                      7   
2c304969-82e6-4981-b2e2-af1f1977b47f                      7   

                                      RETRASO_PAGO_ESTADO_6  \
CLIENT_ID                                                     
29c55f5f-0da7-43ec-ba1b-b60592689825                      0   
f818136a-138f-4578-a0bb-41605b67e0e5                      0   
bef609a9-f9c5-4870-be7f-cb20e70f7e92                      0   
2ba3a218-4792-4672-82c7-4b0953101d41                     -1   
723e61b4-d151-4368-b129-468417fd930c                      0   
f689cc58-4331-40ba-ae4b-c43e649cb9e8                      0   
5366b666-0978-4843-9ad0-a23993b94edd                      0   
92825b72-b828-419b-b2b1-0c4791769558                      0   
bd9b31c5-e0d6-4555-afab-ed6753d6afb8                      7   
2c304969-82e6-4981-b2e2-af1f1977b47f                      7   

                                      RETRASO_PAGO_ESTADO_7  \
CLIENT_ID                                                     
29c55f5f-0da7-43ec-ba1b-b60592689825                      0   
f818136a-138f-4578-a0bb-41605b67e0e5                      0   
bef609a9-f9c5-4870-be7f-cb20e70f7e92                      0   
2ba3a218-4792-4672-82c7-4b0953101d41                     -1   
723e61b4-d151-4368-b129-468417fd930c                      0   
f689cc58-4331-40ba-ae4b-c43e649cb9e8                      0   
5366b666-0978-4843-9ad0-a23993b94edd                     -1   
92825b72-b828-419b-b2b1-0c4791769558                      0   
bd9b31c5-e0d6-4555-afab-ed6753d6afb8                      7   
2c304

In [14]:
data = df.to_numpy()

In [36]:
X,y = data[:,:-1], data[:,-1].astype('int')
X

array([[270000, 'Femenino', 'universidad', ..., 12000, 13000, 10000],
       [80000, 'Femenino', 'colegio', ..., 1200, 1740, 1623],
       [210000, 'Femenino', 'universidad', ..., 6000, 5082, 6483],
       ...,
       [180000, 'Masculino', 'universidad', ..., 2200, 1400, 0],
       [320000, 'Masculino', 'universidad', ..., 739, 1224, 1353],
       [260000, 'Femenino', 'universidad', ..., 0, 0, 1085]], dtype=object)

In [37]:
y


array([0, 0, 0, ..., 0, 0, 0])

### Enconding de variables categoricas 

In [17]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder(sparse=False)
genero = data[:,1]
int_encoded = label_encoder.fit_transform(genero)

In [18]:
int_encoded

array([0, 0, 0, ..., 1, 1, 0])

In [9]:
label_encoder.inverse_transform(int_encoded)

array(['Femenino', 'Femenino', 'Femenino', ..., 'Masculino', 'Masculino',
       'Femenino'], dtype=object)

In [15]:
int_encoded = int_encoded.reshape(-1,1)
onehot_encoded = onehot_encoder.fit_transform(int_encoded)
onehot_encoded

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [20]:
label_encoder.inverse_transform(onehot_encoder.inverse_transform(onehot_encoded).reshape(-1,))


array(['Femenino', 'Femenino', 'Femenino', ..., 'Masculino', 'Masculino',
       'Femenino'], dtype=object)

In [19]:
class CategoricalEncoder():
    """
    Clase que define un calsificador que realiza una transformación de una variable categorica a multiples
    variables dummy (One Hot enconding) y devuelve el codigicador y la codificación

    """

    def __init__(self)->None:
        """
        Método de instanciación de clase
        """
        self.label_encoder = LabelEncoder()
        self.onehot_encoder = OneHotEncoder(sparse=False)

    def fit(self, x:np.ndarray) -> None:
        """
        Método de ajuste del encoder.
        
        Args:
        ----------
        x:np.ndarray
            Arreglo unidimensional con las observaciones de la variable categorica
        """
        label_encoded = self.label_encoder.fit_transform(x).reshape(-1,1)
        onehot_encoder.fit(label_encoded)

    def fit_transform(self, x:np.ndarray) -> np.ndarray:
        """
        Método de ajuste del encoder y transformación de las observaciones de la variable
        categorica.
        
        Args:
        ----------
        x:np.ndarray
            Arreglo unidimensional con las observaciones de la variable categorica

        Results:
        ---------
        np.ndarray
            Arreglo multidimensional con el resultado de la transformación
        """
        label_encoded = self.label_encoder.fit_transform(x).reshape(-1,1)
        onehot_encoded = onehot_encoder.fit_transform(label_encoded)

        return onehot_encoded
    
    def transform(self, x:np.ndarray) -> np.ndarray:
        """
        Método de transformación de las observaciones de la variable categorica.
        
        Args:
        ----------
        x:np.ndarray
            Arreglo unidimensional con las observaciones de la variable categorica

        Results:
        ---------
        np.ndarray
            Arreglo multidimensional con el resultado de la transformación
        """
        label_encoder = self.label_encoder.transform(x).reshape(-1,1)
        onehot_encoded = onehot_encoder.transform(label_encoder)

        return onehot_encoded
    
    def inverse_transform(self, X:np.ndarray) -> np.ndarray:   
        """
        Método de transformación inversa de las codificaciones a la variable original.
        
        Args:
        ----------
        X:np.ndarray
            Arreglo multidimensional con el resultado de la transformación           

        Results:
        ---------
        np.ndarray
            Arreglo unidimensional con las observaciones de la variable categorica
        """

        return label_encoder.inverse_transform(onehot_encoder.inverse_transform(X).reshape(-1,))

In [20]:
genero
genero_encoder = CategoricalEncoder()
genero_encoded = genero_encoder.fit_transform(genero)

In [32]:
np.concatenate([X,genero_encoded], axis = 1)

array([[270000, 'Femenino', 'universidad', ..., 10000, 1.0, 0.0],
       [80000, 'Femenino', 'colegio', ..., 1623, 1.0, 0.0],
       [210000, 'Femenino', 'universidad', ..., 6483, 1.0, 0.0],
       ...,
       [180000, 'Masculino', 'universidad', ..., 0, 0.0, 1.0],
       [320000, 'Masculino', 'universidad', ..., 1353, 0.0, 1.0],
       [260000, 'Femenino', 'universidad', ..., 1085, 1.0, 0.0]],
      dtype=object)

In [21]:
from typing import List

def codificar_categoricas(
        X:np.ndarray
    ):
    """
    Función que codifica las variables categoricas del conjunto de datos
    en columnas de variables indicadoras

    Args:
    ----------
        X:np.ndarray
            Arreglo multidimensional con las observaciones de las variables independientes
        var_columns:List[int]
            Lista con los indices columna de las variables categoricas a codificar
        encoders:List[CategoricalEncoder]
            Lista con los encoders de las columnas previamente ajustados
    """
    genero = X[:,1]
    genero_encoder = CategoricalEncoder()
    genero_encoded = genero_encoder.fit_transform(genero)

    educacion = X[:,2]
    educacion_encoder = CategoricalEncoder()
    educacion_encoded = educacion_encoder.fit_transform(educacion)

    estado_civil = X[:,3]
    estado_civil_encoder = CategoricalEncoder()
    estado_civil_encoded = estado_civil_encoder.fit_transform(estado_civil)

    X = np.delete(X,[1,2,3],1)
    X = np.concatenate([X,genero_encoded], axis=1)
    X = np.concatenate([X,educacion_encoded], axis=1)
    X = np.concatenate([X,estado_civil_encoded], axis=1)
    
    return X


In [22]:
X_encoded = codificar_categoricas(X)

In [23]:
X_encoded.shape

(24000, 33)

In [24]:
X.shape

(24000, 23)

## Escalando las covariables 

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X_encoded)

## Datos de entrenamiento y prueba

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=1)

X_train.shape

(19200, 33)

In [42]:
X_train

array([[-1.13754196,  0.38246756,  0.25514665, ..., -0.91632109,
        -0.10155599,  0.93917928],
       [-1.13754196,  1.03394592, -1.47833377, ...,  1.09132051,
        -0.10155599, -1.06475944],
       [ 2.24825754, -0.37759052,  0.25514665, ..., -0.91632109,
        -0.10155599,  0.93917928],
       ...,
       [ 0.94010773,  0.27388784,  0.25514665, ...,  1.09132051,
        -0.10155599, -1.06475944],
       [-0.29109209, -0.92048916, -1.47833377, ..., -0.91632109,
        -0.10155599,  0.93917928],
       [ 1.86350759,  0.05672838, -0.61159356, ...,  1.09132051,
        -0.10155599, -1.06475944]])

## Balanceo

In [43]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter 

over_sampler = SMOTE(random_state=1)
under_sampler = RandomUnderSampler(random_state=1)

print("Distribución de clases antes del balanceo: ", Counter(y_train))

X_os, y_os = over_sampler.fit_resample(X_train, y_train)
X_us, y_us = under_sampler.fit_resample(X_train, y_train)

print("Distribución de clases con sobre muestreo: ", Counter(y_os))
print("Distribución de clases con sub muestreo: ", Counter(y_us))

Distribución de clases antes del balanceo:  Counter({0: 14953, 1: 4247})
Distribución de clases con sobre muestreo:  Counter({1: 14953, 0: 14953})
Distribución de clases con sub muestreo:  Counter({0: 4247, 1: 4247})


## Diseño de función de procesamiento en la clase del clasificador

In [50]:
import os
import sys

import numpy as np

from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
from typing import Optional

home_path = os.path.dirname(os.getcwd())
sys.path.append(home_path)

surce_path = os.path.join(os.path.dirname(os.getcwd()),'src')
sys.path.append(home_path)

from src.data_management import obtener_datos

class ClasificadorMora():
    """
    Clase que define el clasificador de mora y que arrojará las probabilidades
    de mora y las etiquetas, así como métricas de evaluación
    """

    def __init__(self,
        path_etiquetas:str, 
        path_info_clientes:str, 
        path_hist_transacciones:str,
        test_size:Optional[float]=0.2,
        balance_strategy:Optional[str]=None
    ):
        """
        Método de instanciación de clase.

        Args:
        ----------
        path_etiquetas:str
            Archivo (con su ruta) en que se encuentran los clientes y su respectiva etiqueta de si entra o no en mora        
        path_info_clientes:str
            Archivo (con su ruta) en que se encuentra la información de los clientes
        path_hist_transacciones:str
            Archivo (con su ruta) en que se encuentra el historial transaccional de los últimos 6 meses del cliente
        test_size:float
            Proporción de elementos a incluir en el conjunto de evaluación
        balance_srategy:Optional[str]=None
            Estrategia de balanceo si se desea usar una. Las opciones son "over_sample" y "under_sample".
        """

        self.path_etiquetas = path_etiquetas
        self.path_info_clientes = path_info_clientes
        self.path_hist_transacciones = path_hist_transacciones
        self.test_size = test_size

        if balance_strategy is not None:
            assert balance_strategy.lower() in ["over_sample", "under_sample"], "Las opciones válidas para el balance strategy son 'over_sample' y 'under_sample'."
        self.balance_strategy = balance_strategy

    def codificar_categoricas(self,
            X:np.ndarray
        ):
        """
        Método que codifica las variables categoricas del conjunto de datos
        en columnas de variables indicadoras

        Args:
        ----------
            X:np.ndarray
                Arreglo multidimensional con las observaciones de las variables independientes
        """
        genero = X[:,1]
        self.genero_encoder = CategoricalEncoder()
        genero_encoded = self.genero_encoder.fit_transform(genero)

        educacion = X[:,2]
        self.educacion_encoder = CategoricalEncoder()
        educacion_encoded = self.educacion_encoder.fit_transform(educacion)

        estado_civil = X[:,3]
        self.estado_civil_encoder = CategoricalEncoder()
        estado_civil_encoded = self.estado_civil_encoder.fit_transform(estado_civil)

        X = np.delete(X,[1,2,3],1)
        X = np.concatenate([X,genero_encoded], axis=1)
        X = np.concatenate([X,educacion_encoded], axis=1)
        X = np.concatenate([X,estado_civil_encoded], axis=1)
        
        return X
    
    def preprocess(self):
        """
        Método que preprocesa los datos y devuelve los conjuntos de entrenamiento y prueba
        """

        df = obtener_datos(self.path_etiquetas, self.path_info_clientes, self.path_hist_transacciones)
        data = df.to_numpy()
        X,y = data[:,:-1], data[:,-1].astype('int')

        X = self.codificar_categoricas(X)
        
        self.scaler = StandardScaler()
        X = self.scaler.fit_transform(X_encoded)
        
        X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=self.test_size, random_state=1)

        if self.balance_strategy is not None:
            if self.balance_strategy.lower() == 'over_sample':
                over_sampler = SMOTE(random_state=1)
                X_train, y_train = over_sampler.fit_resample(X_train, y_train)
            
            if self.balance_strategy.lower() == 'under_sample':
                under_sampler = RandomUnderSampler(random_state=1)
                X_train, y_train = under_sampler.fit_resample(X_train, y_train)

        return X_train, X_test, y_train, y_test

In [51]:
path_etiquetas = os.path.join(home_path, 'data', 'etiquetas.csv')
path_info_clientes = os.path.join(home_path, 'data', 'informacion_clientes.csv')
path_hist_transacciones = os.path.join(home_path, 'data', 'historial_transacciones.csv')

clasificador = ClasificadorMora(
    path_etiquetas,
    path_info_clientes,
    path_hist_transacciones    
)

X_train, X_test, y_train, y_test = clasificador.preprocess()

In [52]:
X_train

array([[-1.13754196,  0.38246756,  0.25514665, ..., -0.91632109,
        -0.10155599,  0.93917928],
       [-1.13754196,  1.03394592, -1.47833377, ...,  1.09132051,
        -0.10155599, -1.06475944],
       [ 2.24825754, -0.37759052,  0.25514665, ..., -0.91632109,
        -0.10155599,  0.93917928],
       ...,
       [ 0.94010773,  0.27388784,  0.25514665, ...,  1.09132051,
        -0.10155599, -1.06475944],
       [-0.29109209, -0.92048916, -1.47833377, ..., -0.91632109,
        -0.10155599,  0.93917928],
       [ 1.86350759,  0.05672838, -0.61159356, ...,  1.09132051,
        -0.10155599, -1.06475944]])

In [53]:
Counter(y_train)

Counter({1: 4247, 0: 14953})